'use client';
import React from 'react';
import { Button } from '../ui/button';
import { createClient } from '@/lib/supabase/client';

const slugList = [
	'001_i-smiled-today-too',
	'1-preparing-for-travel-chiang-mai-trip',
	'1-purpose-of-travel-northern-kyushu-train',
	'10-bangkok-dip-chiang-mai-travel-story',
	'10-futatsuboshi-4047-northern-kyushu-train',
	'100-million-won-collected',
	'11-ending-the-trip-northern-kyushu-train',
	'11-thailand-life-impressions-chiang-mai-trip',
	'1st-quarter-2023',
	'1st-quarter-2024',
	'2-voice-of-future-self-chiang-mai-travel',
	'2-woodang-tangtang-entry-story-northern-kyushu-train',
	'2022-memoir-1-about-me',
	'2022-memoir-2-about-career',
	'2022-memoir-3-about-the-company',
	'2022-memoir-4-about-money',
	'2022-memoir-5-about-human-relationships',
	'2022-retrospective-epilo',
	'2022-retrospective-ready',
	'2nd-quarter-2024',
	'2nd-quarter-of-2023',
	'3-after-all-its-rain-northern-kyushu-train',
	'3-what-do-you-do-when-you-have-fun-chiang-mai-travel',
	'3rd-quarter-2023',
	'4-explore-kitakyushu-northern-kyushu-train-station',
	'4-happiness-is-closer-than-you-think-chiang-mai-trip',
	'5-attack-in-earnest-chiang-mai-trip',
	'5-beppu-hell-pilgrimage-northern-kyushu-train',
	'6-kumamoto-north-kyushu-train-station',
	'6-somehow-club-chiang-mai-trip',
	'7-shimabara-line-northern-kyushu-train-station',
	'7-what-do-you-think-jazz-is-chiang-mai-travel',
	'8-getting-to-know-elephants-chiang-mai-trip',
	'8-shimabara-travel-northern-kyushu-train',
	'9-choose-romance-over-practicality-chiang-mai-trip',
	'9-seeing-nagasaki-north-kyushu-train-station',
	'a-developer-is-a-person-who-can-solve-problems-with-technology',
	'a-place-to-rest-teneri',
	'a-poem-about-traveling',
	'a-rare-infj-trip-to-spain-jun',
	'a-whopping-two-hours-of-refresh',
	'about-developer-growth',
	'about-poverty',
	'after-open-source-contributor',
	'after-rotc',
	'after-taking-a-year-off-and-going-back-to-work',
	'after-trevary',
	'all-life-flows',
	'app-version',
	'arbitrary-judgment-false-reporting-and-disguised-forces',
	'axios-error',
	'barcelo-a-city-filled-with-light',
	'be-a-good-colleague',
	'be-honest-but-not-rude',
	'black-persimmon',
	'blockchain-digital-agora-and-the-beauty-of-politics',
	'breadcrum',
	'burnout-and-slums',
	'change-of-job-for-a-2nd-year-developer',
	'change-of-job-for-a-3-year-developer',
	'clarity',
	'clear-from-slack',
	'columbus-month',
	'company-selection-guide-for-startup-engineers-2',
	'company-selection-guide-for-startup-engineers',
	'conference-room',
	'defense-mechanism-arising-from-deficiency',
	'determine-personal-metrics',
	'developer-resume',
	'developers-resume',
	'development-as-a-service-creator',
	'development-becomes-a-problem-solving-tool-like-scissors',
	'development-that-works-well',
	'digital-building',
	'docusaurus-blog',
	'eat-frog-and-five-apples',
	'eating-a-frog-and-five-fours',
	'email-phobia',
	'error-experience',
	'event-tracking-module',
	'everything-everywhere-all-at-on',
	'fetch',
	'fill-the-day-with-positivity',
	'functional-programming',
	'git-command',
	'git',
	'goldfish-in-fish-tank',
	'good-at-work-developer',
	'graphql-architecture',
	'great-developer',
	'grow-up',
	'have-a-good-week',
	'i-left-the-company',
	'i-might-be-wrong',
	'i-smiled-today-too',
	'instinct-modernity-and-the-relief-of-our-brains',
	'introverts-dance-actor',
	'leger-learned-from-master-chae',
	'lets-deviate-from-the-plan',
	'leverage',
	'library',
	'making-a-trip-a-trip',
	'modal',
	'motorcycle-company-in-vietnam',
	'nf',
	'no-one-can-destroy-me',
	'occupation-view-in-the-ai-era-developer',
	'office-life-postmo',
	'on-the-flight-home',
	'optional-chaining',
	'personal-ok',
	'planning-a-trip',
	'platform-business',
	'pm-experience',
	'power-js-no-plan',
	'react-query',
	'record-of-reading',
	'reduce-your-dependence-on-your-smartphone',
	'refactoro',
	'remove-company-from-business-card',
	'retrospective',
	'revery',
	'sentry',
	'seo-raise-click',
	'sitemap',
	'so-how-will-we-live-in-2023',
	'someone-who-has-spent-money-spends-it-too',
	'speak-nicely',
	'spend-all-your-money',
	'spend-less-and-earn-more',
	'take-the-company-name-off-the-business-card',
	'teach-someone',
	'technical-conqueror',
	'the-ability-to-rest',
	'the-beauty-of-metaverse-and-cryptocurrency',
	'the-door-that-does-not-blame-mistakes',
	'the-pros-and-cons-of-a-purpose-driven-organization',
	'the-result-is-clearly-visible',
	'the-right-decision-may-not-have-been-right',
	'the-role-of-emotions-in-motivation',
	'thumbhash',
	'time-management-after-leaving-the-company',
	'to-solve-bigger-problems',
	'to-those-who-have-forgotten-how-to-cry',
	'tools-of-the-titan',
	'typeguard',
	'unconventional-success-principles',
	'use-all-your-money-time-and-courage',
	'use-imperactive-handle-modal',
	'webview-connection',
	'what-do-people-live-by',
	'what-is-good-communication',
	'what-is-work',
	'what-makes-a-good-developer',
	'why-i-am-abandoning-my-blog',
	'why-work',
	'workflow',
];

const MagicButton = () => {
	const updateAllData = async () => {
		const supabase = createClient();
		slugList.forEach(slug => {
			const thumbnailUrl = `https://www.hojunin.com/contents/${slug}/opengraph-image`;

			supabase
				.from('contents')
				.update({ thumbnail: thumbnailUrl })
				.eq('slug', slug)
				.is('thumbnail', null)
				.then(() => console.log('성공 : ', slug));
		});
	};
	return <Button onClick={updateAllData}>마법의 버튼</Button>;
};

export default MagicButton;
